### ISSUE TITLE
Not Super Clear On Instructions

### ISSUE THREAD

**Issue by grandballoon** [learn-co-curriculum/react-props-movie-lab#1]
I think a lot of us are having trouble understanding what exactly this lab is asking us to do. A lot of the syntax is things we've never seen before, and I and others had a lot of trouble following the instructions. There's also an unnecessary empty string inside the interpolation brackets of the URL for the poster.

**Comment by SilverBright** [comment]
This lab should be converted to a code-a-long.

**Comment by maxwellbenton** [comment]
Hi @grandballoon,

Thank you for providing this feedback. We've updated this lesson's instructions to be much more guided and to introduce concepts like mapping to return components, which should help make this lab more approachable and useful as a learning tool.

We apologize for and frustration this lab may have caused you, but we appreciate you taking the time to give feedback and help improve this content for future students.

Thank you!
