### ISSUE TITLE
Instructions Unclear and Generally Too Difficult

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/react-props-movie-lab#4]
The objective of this lab was not explained. Methods were not explained such as .map() and `<img src={imgMapper[prop]} alt="" />`. We never learned how to debug with React so I don't know what to do when I get an error. I think it's pretty much impossible to pass this lab without looking at the answer because these concepts weren't explained.

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thank you for providing this feedback. We've updated this lesson's instructions to be much more guided and to introduce concepts like mapping to return components, which should help make this lab more approachable and useful as a learning tool.

We apologize for and frustration this lab may have caused you, but we appreciate you taking the time to give feedback and help improve this content for future students.

Thank you!
